name: fisioflex_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  dio: ^5.3.2
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_tts: ^3.8.3
  hooks_riverpod: ^2.3.7
  shared_preferences: ^2.2.1
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  #assets image
  assets:
    - assets/
    - assets/images/
    - assets/icons/
