name: fisioflex_mobile
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-262.2.beta <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  hooks_riverpod: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  #assets image
  assets:
    - assets/
    - assets/images/
    - assets/icons/
