// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGRKb1247rMrAWlohRIkwdysHgpyva3Jk',
    appId: '1:345379941326:web:d8d566fc67bebd8775d99f',
    messagingSenderId: '345379941326',
    projectId: 'iq-sos-prototype',
    authDomain: 'iq-sos-prototype.firebaseapp.com',
    storageBucket: 'iq-sos-prototype.appspot.com',
    measurementId: 'G-YRD1HCMELX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCQv7vwDo8Vvjf1zr0qMVQBQTtLfbgSA',
    appId: '1:345379941326:android:cdee7443758d224e75d99f',
    messagingSenderId: '345379941326',
    projectId: 'iq-sos-prototype',
    storageBucket: 'iq-sos-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCTXIZWU-ZnKm9Q-LsyZx1RBt61voy09w',
    appId: '1:345379941326:ios:ac138c254d2483d975d99f',
    messagingSenderId: '345379941326',
    projectId: 'iq-sos-prototype',
    storageBucket: 'iq-sos-prototype.appspot.com',
    iosClientId: '345379941326-t6hk37f88293edr0fpu04jbh53l8mclu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fisioflexMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCTXIZWU-ZnKm9Q-LsyZx1RBt61voy09w',
    appId: '1:345379941326:ios:a144c3efe13c8bf275d99f',
    messagingSenderId: '345379941326',
    projectId: 'iq-sos-prototype',
    storageBucket: 'iq-sos-prototype.appspot.com',
    iosClientId: '345379941326-ni0nbbmlckjbglgajkg0j1972ng8popv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fisioflexMobile.RunnerTests',
  );
}
